apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemon-set
  namespace: mateapp
  labels:
    app: test-daemon-set
spec:
  selector:
    matchLabels:
      app: busyboxplus
  template:
    metadata:
      labels:
        app: busyboxplus
    spec:
      containers:
      - name: busyboxplus
        image: busyboxplus:curl
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "--- $(date) ---"
            curl -i http://todoapp-service.todoapp.svc.cluster.local:80
            sleep 5
          done
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"